[config.wallpaper]
command = "null"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.waybar]
input_path = "./templates/colors-waybar.css"
output_path = "~/.config/waybar/wallust/colors-waybar.css"

[templates.kitty]
input_path="./templates/colors-kitty.conf"
output_path="~/.config/kitty/wallust/kitty.conf"

[templates.cava]
input_path="./templates/colors-cava"
output_path="~/.config/cava/config"

[templates.hyprland]
input_path="./templates/colors-hyprland.conf"
output_path="~/.config/hypr/wallust/wallust-hyprland.conf"
