theme="base16_transparent"
[editor.soft-wrap]
enable=true

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor]
# color-modes=true
# mouse=false
# line-number="relative"
# gutters = ["diagnostics", "spacer", "diff"]

[editor.statusline]
separator="|"
mode.normal="N"
mode.insert="I"
mode.select="V"
left = ["diagnostics", "position","file-name"]
center=[]
right=[]
# right=[]
# center=[]


[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line="warning"


