theme="base16_transparent"
[editor.soft-wrap]
enable=true

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor]
color-modes=true
mouse=true
line-number="relative"

[editor.statusline]
separator="angle"
mode.normal="NORMAL"
mode.insert="INSERT"
mode.select="VISUAL"

