[language-server.omnisharp]
command="omnisharp"

[language-server]
yuckls = {command="yuckls"}
ols = {command = "/home/noble/.local/share/nvim/mason/bin/ols"}
avalonials = {command="avalonia-ls"}

[[language]]
name="yuck"
scope="source.yuck"
injection-regex="yuck"
file-types=["yuck"]
language-servers = ["yuckls"]

[[language]]
name="xml"
scope="source.axaml"
injection-regex="axaml"
file-types=["axaml"]
language-servers=["avalonials"]
grammar="xml"
auto-format=true
formatter={command="xaml-styler",args=["--write-to-stdout" ,"--take-pipe"]}

