[language-server.omnisharp]
command="omnisharp"

[language-server]
yuckls = {command="yuckls"}

[[language]]
name="yuck"
scope="source.yuck"
injection-regex="yuck"
file-types=["yuck"]
language-servers = ["yuckls"]

[keys.normal]
C-a="goto_line_end_newline"
0="goto_line_start"
